name: PlatformIO CI

on: [push, pull_request]

jobs:
  native-test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Run PlatformIO
        run: |
          pio test -e native


  build-native:
    runs-on: ubuntu-latest

    steps:
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Run PlatformIO
        run: |
          pio run -e native

  build-esp32:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Run PlatformIO
        run: |
          pio run -e release